AWSTemplateFormatVersion: 2010-09-09
Description: testing
Parameters:
    DomainName:
        Description: Name of the domain to be configured
        Type: String
        ConstraintDescription: Must be a valid string. Just introduce the domain name.
    DomainHostedZoneId:
        Description: Name of the HostedZoneId for the current Domain
        Type: String
    S3HostedZoneId:
        Description: Name of the HostedZoneId for the current s3 region
        Type: String
Resources:
    HostingBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: 
            Ref: DomainName
        MetricsConfigurations: 
          - Id: EntireBucket
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
    HostingBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
          Bucket: !Ref HostingBucket
          PolicyDocument:
            Statement:
                Effect: Allow
                Principal: "*"
                Action: s3:GetObject
                Resource: !Join ['', ['arn:aws:s3:::', !Ref HostingBucket, '/*']] 
            Statement:
                Effect: Deny
                Principal: "*"
                Action: s3:GetObject
                Resource : !Join ['', ['arn:aws:s3:::', !Ref HostingBucket, '/mail/*']]
    HostingBucketRecord:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: !Ref DomainHostedZoneId
            Name: !Ref DomainName
            Type: A
            AliasTarget:
                DNSName: s3-website-eu-west-1.amazonaws.com.
                HostedZoneId: !Ref S3HostedZoneId
            