

service: serverless-email

plugins:
    - serverless-python-requirements
    
provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  enviroment:
    DOMAIN: pablovoorvaart.me

functions:
  recive:
    handler: src/recive.recive


